  <% require "dotenv"; Dotenv.load(".env") %>

  service: empire-des-amis-country

  image: tegbessou/empire-des-amis-country

  deploy_timeout: 60

  servers:
    web:
      hosts:
        - 5.189.149.68

  retain_containers: 2

  proxy:
    ssl: false
    host: 5.189.149.68
    app_port: 8082
    healthcheck:
      path: /api/up

  registry:
    username: tegbessou
    password:
      - KAMAL_REGISTRY_PASSWORD

  builder:
    arch: amd64
    context: .
    dockerfile: ./docker/prod/Dockerfile
    remote: ssh://root@5.189.149.68

  ssh:
    user: root
    keys_only: false
    keys: [ "~/.ssh/id_rsa" ]

  volumes:
    - /home/root/volumes/country:/app/var/log:rw

  env:
    clear:
      APP_ENV: prod
      APP_SECRET: 8d0451fe0062d77cef08eeba1de40b1f
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
      JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
      JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'
      MONGODB_DB: 'eda_country'
    secret:
      - DATABASE_URL
      - JWT_PASSPHRASE
      - MONGODB_URL

  labels:
    traefik.enable: "true"
    traefik.http.routers.empire-des-amis-user.rule: "PathPrefix(`/country/api`)"
    traefik.http.routers.empire-des-amis-user.entrypoints: "web"
    traefik.http.services.empire-des-amis-user.loadbalancer.server.port: "8082"
    traefik.http.routers.empire-des-amis-user.middlewares: "strip-prefix"
    traefik.http.middlewares.strip-prefix.stripPrefix.prefixes: "/country"
