parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $kernelProjectDirectory: '%kernel.project_dir%'

    EmpireDesAmis\Country\:
        resource: '../src/'

    EmpireDesAmis\Country\Application\Projection\CreateCountryProjection:
        tags: [kernel.event_listener]

when@dev:
    services:
        EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
            alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase

when@test:
    services:
        EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
            alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase